name: on-it
services:
  - name: on-it
    github:
      repo: VladStoenescu/ON-IT
      branch: main
      deploy_on_push: true
    build_command: npm ci --omit=dev
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: DB_HOST
        scope: RUN_TIME
        value: app-b577de97-4d36-493c-981c-d7faa5c293ee-do-user-27694528-0.d.db.ondigitalocean.com
      - key: DB_PORT
        scope: RUN_TIME
        value: "25060"
      - key: DB_USER
        scope: RUN_TIME
        value: onpointbackoffice
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        scope: RUN_TIME
        value: onpointbackoffice
